---
- name: Install Docker and Docker-compose and Gitlab-runner
  hosts: gitlab
  become: true
  gather_facts: true

  tasks:
    - name: Update package repositories
      apt:
        update_cache: yes
      become: true

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - ca-certificates
        - apt-transport-https
        - software-properties-common
        - lsb-release
      become: true

    - name: Add Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      become: true

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present
      become: true
    
    - name: Install Docker packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      become: true

    - name: Change permissions for docker.sock
      file:
        path: /var/run/docker.sock
        mode: '0777'
      become: true

    - name: Install Docker Compose
      shell: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
      become: true

    - name: Add GitLab's official repository
      shell: curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | bash
      become: true
      
    - name: Install GitLab Runner
      become: true
      apt:
        name: gitlab-runner
        state: present

    - name: Register the runner with GitLab
      command: gitlab-runner register
        --non-interactive
        --url https://18.143.159.100/
        --registration-token glrt-Y8Vx6pwMe1RB4_y1pRuB
        --executor shell

    - name: Start GitLab Runner service
      service:
        name: gitlab-runner
        state: started

